# Generated by Django 4.2.9 on 2024-03-21 05:49

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = []

    operations = [VectorExtension()]
