# Generated by Django 4.2.9 on 2024-03-21 05:49

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django
import shortuuidfield.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ezra", "0001_enable_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="PodcastEpisode",
            fields=[
                (
                    "uid",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_modified", models.DateTimeField(auto_now=True)),
                ("date", models.DateTimeField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("details_url", models.CharField(max_length=2048)),
                ("slug", models.SlugField(blank=True, max_length=250, null=True)),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="audio_files"),
                ),
                ("audio_url", models.CharField(max_length=2048)),
                ("resolved_audio_url", models.CharField(max_length=2048)),
                (
                    "transcription",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                (
                    "transcription_full_text",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "whisper_model_size",
                    models.CharField(
                        choices=[
                            ("tiny", "tiny"),
                            ("base", "base"),
                            ("small", "small"),
                            ("medium", "medium"),
                            ("large", "large"),
                        ],
                        default="base",
                        max_length=10,
                    ),
                ),
                (
                    "whisper_transcription_object",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PodcastEpisodeEmbedding",
            fields=[
                (
                    "uid",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_modified", models.DateTimeField(auto_now=True)),
                ("embedding", pgvector.django.VectorField(dimensions=1024)),
                (
                    "podcast_episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ezra.podcastepisode",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
